<a href="https://colab.research.google.com/github/paulordie/aquis-preproc-explo-dados/blob/master/Exerc%C3%ADcio_01_paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1 - Importação das bibliotecas

In [46]:
import requests
import json
import pandas as pd

In [47]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

##1.1 Carregamento do DataFrame flags.csv

In [48]:
pd_flags = pd.read_csv('/content/drive/MyDrive/flags_.csv',sep=',')

In [63]:
pd_flags.head()

             name  landmass  zone  area  ...  animate  text  topleft  botright
0     Afghanistan         5     1   648  ...        0     0    black     green
1         Albania         3     1    29  ...        1     0      red       red
2         Algeria         4     1  2388  ...        0     0    green     white
3  American-Samoa         6     3     0  ...        1     0     blue       red
4         Andorra         3     1     0  ...        0     0     blue       red

[5 rows x 30 columns]

In [64]:
list_flags = list(pd_flags.columns)
ar_flags = []
for x in list_flags:
  ar_flags.append(x)
print(ar_flags)
print(len(ar_flags))

['name', 'landmass', 'zone', 'area', 'population', 'language', 'religion', 'bars', 'stripes', 'colours', 'red', 'green', 'blue', 'gold', 'white', 'black', 'orange', 'mainhue', 'circles', 'crosses', 'saltires', 'quarters', 'sunstars', 'crescent', 'triangle', 'icon', 'animate', 'text', 'topleft', 'botright']
30

##1.2 Carregamento do DataFrame countries.csv

In [50]:
pd_countries = pd.read_csv('/content/drive/MyDrive/countries.csv', sep = ';')

In [61]:
pd_countries.head()

  alpha_2 alpha_3  ...  postal_code_regex  tld,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0      AD     AND  ...   ^(?:AD)*(\d{3})$   .ad,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1      AE     ARE  ...                NaN       .ae,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2      AF     AFG  ...                NaN          .af,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3      AG     ATG  ...                NaN  .ag,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4      AI     AIA  ...                NaN  .ai,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

[5 rows x 19 columns]

In [62]:
list_countries = list(pd_countries.columns)
ar_countries = []
for x in list_countries:
  ar_countries.append(x)
print(ar_countries)
print(len(ar_countries))

['alpha_2', 'alpha_3', 'area', 'capital', 'continent', 'currency_code', 'currency_name', 'eqivalent_fips_code', 'fips', 'geoname_id', 'languages', 'name', 'neighbours', 'numeric', 'phone', 'population', 'postal_code_format', 'postal_code_regex', 'tld,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,']
19

##1.3 Carregamento do DataFrame na API RestCountries

In [59]:
def reqCountriesAll():
  res = requests.get('https://restcountries.eu/rest/v2/all')
  if res.status_code == 200:
    # return res.json()
    _restcountries = res.json()
    pd_restcountries = pd.DataFrame.from_dict(_restcountries)
    return pd_restcountries
  else:
    print(f'Erro {res.status_code} : "{res.reason}"')

pd_restcountries =  reqCountriesAll()
pd_restcountries.head()

             name  ... cioc
0     Afghanistan  ...  AFG
1   Åland Islands  ...
2         Albania  ...  ALB
3         Algeria  ...  ALG
4  American Samoa  ...  ASA

[5 rows x 24 columns]

In [60]:
list_restcountries = list(pd_restcountries.columns)
ar_restcountries = []
for x in list_restcountries:
  ar_restcountries.append(x)
print(ar_restcountries)
print(len(ar_restcountries))

['name', 'topLevelDomain', 'alpha2Code', 'alpha3Code', 'callingCodes', 'capital', 'altSpellings', 'region', 'subregion', 'population', 'latlng', 'demonym', 'area', 'gini', 'timezones', 'borders', 'nativeName', 'numericCode', 'currencies', 'languages', 'translations', 'flag', 'regionalBlocs', 'cioc']
24

##2.1 Verificação se não está no flags.csv

In [58]:
pd_only_flags = pd_flags[pd_flags.name.isin(pd_countries.name) == False]
pd_only_flags

                     name  landmass  zone  ...  text  topleft  botright
3          American-Samoa         6     3  ...     0     blue       red
7         Antigua-Barbuda         1     4  ...     0    black       red
9               Argentine         2     3  ...     0     blue      blue
24   British-Virgin-Isles         1     4  ...     1    white      blue
27                Burkina         4     4  ...     0      red     green
..                    ...       ...   ...  ...   ...      ...       ...
184                  USSR         5     1  ...     0      red       red
186          Vatican-City         3     1  ...     0     gold     white
189         Western-Samoa         6     3  ...     0     blue       red
190            Yugoslavia         3     1  ...     0     blue       red
191                 Zaire         4     2  ...     0    green     green

[61 rows x 30 columns]

##2.1 Verificação se não está no DataFrame RestCountries

In [65]:
pd_only_restcountries = pd_restcountries[pd_restcountries.name.isin(pd_countries.name)==False]
pd_only_restcountries

                                                  name  ...  cioc
1                                        Åland Islands  ...
26                    Bolivia (Plurinational State of)  ...   BOL
27                    Bonaire, Sint Eustatius and Saba  ...  None
34                            Virgin Islands (British)  ...   IVB
35                               Virgin Islands (U.S.)  ...   ISV
36                                   Brunei Darussalam  ...   BRU
43                                          Cabo Verde  ...   CPV
50                             Cocos (Keeling) Islands  ...
53                                               Congo  ...   CGO
54                  Congo (Democratic Republic of the)  ...   COD
59                                             Curaçao  ...
61                                      Czech Republic  ...   CZE
73                         Falkland Islands (Malvinas)  ...
99                                            Holy See  ...
106                                      Côte d'Ivoire  ...   CIV
107                         Iran (Islamic Republic of)  ...   IRI
122                   Lao People's Democratic Republic  ...   LAO
132        Macedonia (the former Yugoslav Republic of)  ...   MKD
145                   Micronesia (Federated States of)  ...   FSM
146                              Moldova (Republic of)  ...   MDA
165            Korea (Democratic People's Republic of)  ...   PRK
171                                Palestine, State of  ...   PLE
182                                 Republic of Kosovo  ...  None
183                                            Réunion  ...
185                                 Russian Federation  ...   RUS
187                                   Saint Barthélemy  ...
188       Saint Helena, Ascension and Tristan da Cunha  ...  None
191                         Saint Martin (French part)  ...
203                          Sint Maarten (Dutch part)  ...
210                                Korea (Republic of)  ...   KOR
220                               Syrian Arab Republic  ...   SYR
223                       Tanzania, United Republic of  ...   TAN
225                                        Timor-Leste  ...   TLS
238  United Kingdom of Great Britain and Northern I...  ...   GBR
239                           United States of America  ...   USA
243                 Venezuela (Bolivarian Republic of)  ...   VEN
244                                           Viet Nam  ...   VIE

[37 rows x 24 columns]

##3 - Inclusão de todos os dados

In [43]:
flags_and_countries = pd.merge(pd_flags, pd_countries, left_on='name', right_on='name', how='left')
# flags_and_countries.head()
flags_and_countries.head()

             name  ...  tld,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0     Afghanistan  ...          .af,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1         Albania  ...       .al,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2         Algeria  ...        .dz,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3  American-Samoa  ...                                      NaN
4         Andorra  ...   .ad,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

[5 rows x 48 columns]

In [66]:
pd_all_countries = pd.merge(flags_and_countries, pd_restcountries, left_on='name', right_on='name', how='left')
# flags_and_countries.head()
pd_all_countries.head()

             name  ...  cioc
0     Afghanistan  ...   AFG
1         Albania  ...   ALB
2         Algeria  ...   ALG
3  American-Samoa  ...   NaN
4         Andorra  ...   AND

[5 rows x 71 columns]

In [67]:
ar_all = []
for x in list(pd_all_countries.columns):
  ar_all.append(x)

print(ar_all)
print(len(ar_all))

['name', 'landmass', 'zone', 'area_x', 'population_x', 'language', 'religion', 'bars', 'stripes', 'colours', 'red', 'green', 'blue', 'gold', 'white', 'black', 'orange', 'mainhue', 'circles', 'crosses', 'saltires', 'quarters', 'sunstars', 'crescent', 'triangle', 'icon', 'animate', 'text', 'topleft', 'botright', 'alpha_2', 'alpha_3', 'area_y', 'capital_x', 'continent', 'currency_code', 'currency_name', 'eqivalent_fips_code', 'fips', 'geoname_id', 'languages_x', 'neighbours', 'numeric', 'phone', 'population_y', 'postal_code_format', 'postal_code_regex', 'tld,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', 'topLevelDomain', 'alpha2Code', 'alpha3Code', 'callingCodes', 'capital_y', 'altSpellings', 'region', 'subregion', 'population', 'latlng', 'demonym', 'area', 'gini', 'timezones', 'borders', 'nativeName', 'numericCode', 'currencies', 'languages_y', 'translations', 'flag', 'regionalBlocs', 'cioc']
71

In [24]:
def reqCountriesName(name):
  res = requests.get('https://restcountries.eu/rest/v2/name/' + name)
  if res.status_code == 200:
    return res.json()
  else:
    print(f'Erro {res.status_code} : "{res.reason}"')

reqCountriesName("Brazil")

[{'alpha2Code': 'BR',
  'alpha3Code': 'BRA',
  'altSpellings': ['BR',
   'Brasil',
   'Federative Republic of Brazil',
   'República Federativa do Brasil'],
  'area': 8515767.0,
  'borders': ['ARG',
   'BOL',
   'COL',
   'GUF',
   'GUY',
   'PRY',
   'PER',
   'SUR',
   'URY',
   'VEN'],
  'callingCodes': ['55'],
  'capital': 'Brasília',
  'cioc': 'BRA',
  'currencies': [{'code': 'BRL', 'name': 'Brazilian real', 'symbol': 'R$'}],
  'demonym': 'Brazilian',
  'flag': 'https://restcountries.eu/data/bra.svg',
  'gini': 54.7,
  'languages': [{'iso639_1': 'pt',
    'iso639_2': 'por',
    'name': 'Portuguese',
    'nativeName': 'Português'}],
  'latlng': [-10.0, -55.0],
  'name': 'Brazil',
  'nativeName': 'Brasil',
  'numericCode': '076',
  'population': 206135893,
  'region': 'Americas',
  'regionalBlocs': [{'acronym': 'USAN',
    'name': 'Union of South American Nations',
    'otherAcronyms': ['UNASUR', 'UNASUL', 'UZAN'],
    'otherNames': ['Unión de Naciones Suramericanas',
     'União de Nações Sul-Americanas',
     'Unie van Zuid-Amerikaanse Naties',
     'South American Union']}],
  'subregion': 'South America',
  'timezones': ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
  'topLevelDomain': ['.br'],
  'translations': {'br': 'Brasil',
   'de': 'Brasilien',
   'es': 'Brasil',
   'fa': 'برزیل',
   'fr': 'Brésil',
   'hr': 'Brazil',
   'it': 'Brasile',
   'ja': 'ブラジル',
   'nl': 'Brazilië',
   'pt': 'Brasil'}}]